.github/workflows/go-test.yaml, .github/workflows/slack-deploy-notification.yaml
pass secrets properly to the ci workflows
=> fix ci workflow call secrets

.github/workflows/go-test.yaml
update the go-test secret name to be consistent with other workflows
=> fix: use consistent secret name

.github/workflows/slack-deploy-notification.yaml
include actor in deployment notification
=> fix: add actor to deployment notification

.github/pull_request_template.md
This updates our PR template. Note this PR is incomplete, and not yet ready for merge. This is motivated by a desire to make our PR merge process more efficient, and to be more explicit in the expectations for engineers, and for mergers. 
This hasn't gone through any testing, but is getting a lot of people's feedback!
No issue link
None
=> Potential update to PR review template.

.github/workflows/go-test.yaml
include mockgen dependency in tool set
=> ci: include mockgen dependency

.github/workflows/openapi-generate-go-client.yaml, .github/workflows/openapi-generate-typescript-client.yaml
add a shared workflow to generate a typescript client from an openapi spec
=> Add typescript client generation workflow

.github/workflows/openapi-generate-typescript-client.yaml
pass the generator config properties through additional properties
=> ci: set npm name through additional properties

.github/workflows/openapi-generate-javascript-client.yaml
Add a workflow to generate a javascript client and publish it to the github package registry
=> feat: add javascript generator workflow

.github/workflows/openapi-generate-javascript-client.yaml
The workflow was not correctly using the javascript generator
=> Javascript not typescript

.github/pull_request_template.md
This change updates the default PR template to be more streamlined, removing a lot of the checklists. 
Per the decision log, the old template was too long and created too much friction, leading to folks completely ignoring it. This new template focuses a lot more on "real talk", which should increase the amount of actionable information in our PRs. 
**Related Decision Log:** https://revolutionparts.slite.com/app/docs/j_yPEXmdDsLO24/Decision-Log-Streamline-Org-Pull-Request-Template
=> feat: more streamlined pr template

.github/workflows/helm-rollback.yaml
Devs need the ability to rollback both bad and failed deployments.
=> feat: add helm rollback action

.github/workflows/php-build-push.yaml, .github/workflows/php-nginx-build-push.yaml
Reusable PHP app and nginx builds.
**Jira Issue:** https://revolutionparts.atlassian.net/browse/DEVX-603
Our projects that only install composer and use an Nginx proxy can benefit from a reusable action to build QA environments.
=> feat: reusable docker builds for v1 php apps

.github/workflows/go-test.yaml
Updated golint to latest version after updating products-api codebase to be compliant with latest golint version 
**Jira Issue:** https://revolutionparts.atlassian.net/browse/SCM-1793
=> chore: updated golint to latest version

.github/workflows/php-common-bump.yaml
=> fix: syntax error in commit message

.github/workflows/php-common-bump.yaml
=> chore: add secret when checking out

.github/workflows/php-common-bump.yaml
=> chore: write pat

.github/workflows/php-common-bump.yaml
update commit message to not run actions
=> chore: do not run other actions when bumping common

.github/workflows/php-laravel-test.yaml, .github/workflows/php-stan.yaml, .github/workflows/php-unit-test.yaml
Update shared workflows that use `upload-artifact` to v4
=> chore: update all upload artifacts to v4

.github/workflows/php-laravel-test.yaml, .github/workflows/php-stan.yaml, .github/workflows/php-unit-test.yaml
v4 doesn't upload hidden files by default
=> fix: upload artifact needs to be told to upload hidden files

.github/workflows/php-laravel-pint.yaml, .github/workflows/php-laravel-test.yaml, .github/workflows/php7-cs-fixer.yaml
Remove the hardcoded PHP versions by allowing the version to be passed in.
=> Remove hardcoded PHP versions
